volumes:
  pg_data:

services:
  postgres:
    restart: always
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: idaweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - $DATA_PATH/sqls/postgres:/docker-entrypoint-initdb.d
       - pg_data:/var/lib/postgresql/data

  web:
    restart: always
    depends_on:
       - postgres
    command: >
      bash -c "sleep 10
      && /opt/ol/wlp/bin/server run defaultServer"
    image: ida:24.0.8
    ports:
      - "9443:9443"
      - "9080:9080"
    environment:
      DATABASE_TYPE: postgres
      JNDI_NAME: jdbc/ida
      DATABASE_NAME: idaweb
      DATABASE_SERVER_NAME: postgres
      DATABASE_PORT_NUMBER: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_MAX_POOL_SIZE: 50
    volumes:
       - $DATA_PATH/ida:/var/ida/data
       - $DATA_PATH/ida/jdbc/postgres/postgresql-42.2.8.jar:/opt/ol/wlp/usr/shared/resources/jdbc/postgres/postgresql-42.2.8.jar
       - $DATA_PATH/ida/jdbc/postgres/postgres.xml:/opt/ol/wlp/usr/servers/defaultServer/postgres.xml

  hub:
    image: selenium/hub:3.141.59-palladium
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 20
      GRID_BROWSER_TIMEOUT: 120
      GRID_TIMEOUT: 60

  chrome:
    image: selenium/node-chrome:3.141.59-palladium
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
    links:
      - hub

  firefox:
    image: selenium/node-firefox:3.141.59-palladium
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
    links:
      - hub
